### ISSUE TITLE
Erreur sur path

### ISSUE THREAD

**Issue by Gorbus** [etalab/dvf#1]
Bonjour,

J'essaie de faire fonctionner ce script de conversion mais je tombe sur l'erreur suivante :

```
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:125:11)
    at join (path.js:1147:7)
    at getParcellesCommune (testFolder/ConvertData/dvf/lib/parcelles.js:11:20)
    at bluebird.map (testFolder/ConvertData/dvf/improve-csv.js:136:33)
    at tryCatcher (testFolder/ConvertData/dvf/node_modules/bluebird/js/release/util.js:16:23)
    at MappingPromiseArray._promiseFulfilled (testFolder/ConvertData/dvf/node_modules/bluebird/js/release/map.js:68:38)
    at MappingPromiseArray.PromiseArray._iterate (testFolder/ConvertData/dvf/node_modules/bluebird/js/release/promise_array.js:115:31)
    at MappingPromiseArray.init (testFolder/ConvertData/dvf/node_modules/bluebird/js/release/promise_array.js:79:10)
    at MappingPromiseArray._asyncInit (testFolder/ConvertData/dvf/node_modules/bluebird/js/release/map.js:37:10)
    at _drainQueueStep (testFolder/ConvertData/dvf/node_modules/bluebird/js/release/async.js:97:12)
    at _drainQueue (testFolder/ConvertData/dvf/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (testFolder/ConvertData/dvf/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues (testFolder/ConvertData/dvf/node_modules/bluebird/js/release/async.js:15:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
```

Pour le faire fonctionner j'ai suivi la démarche suivante:
- cloner le repo
- npm install
- créer un dossier data
- copier les fichiers originaux .txt dans /data
- gzipper ces mêmes fichiers en .txt.gz
- remonter à la source
- node --max-old-space-size=4096 improve-csv.js

Il y a t-il d'autres démarches nécessaires, comme par exemple le changement des dates pour:

 const DATE_ALIGNEMENT = "2019-10-01";
const DATE_ALIGNEMENT_CADASTRE = "2019-10-01";

ou encore d'autres fichiers nécessaires au bon fonctionnement du script ?

Par avance, merci pour votre aide.

**Comment by Gorbus** [comment]
Je pense que mon problème vient des variables d'environnement non déclarées:

```
CADASTRE_COMMUNES_PATH=
DISABLE_GEOCODING=
```

seriez vous me dire quel chemin est attendu pour CADASTRE_COMMUNES_PATH ?

**Comment by jdesboeufs** [comment]
Bonjour,

En effet l'erreur vient de l'absence de variable d'environnement `CADASTRE_COMMUNES_PATH`.
Ce qui est attendu est le chemin vers une arborescence qui contient ces fichiers : https://cadastre.data.gouv.fr/data/etalab-cadastre/2019-07-01/geojson/communes/ (millésime adapté pour la dernière livraison des données DVF qui vient d'arriver aujourd'hui).

Nous allons documenter ce dépôt c'est promis.
